name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master
# workflow trigger
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production --base-href /hm-it-dashboard/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/hm-it-dashbord/browser/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
